### ISSUE TITLE
Issue while running

### ISSUE THREAD

**Issue by btalbot16** [rothman857/chronometer#12]
pi@raspberrypi:~ $ python /home/pi/Downloads/chronometer-master/chronometer.py
  File "/home/pi/Downloads/chronometer-master/chronometer.py", line 74
    print("\033[0;0H", end="")
                          ^
SyntaxError: invalid syntax
 
got this error while trying to run program, don't know if the code's bad or if i'm doing it wrong.
The syntax error is at the , end="") bit

**Comment by rothman857** [comment]
I think you're running python 2.x. This code was written in python3.
