### ISSUE TITLE
Some detail missing?

### ISSUE THREAD

**Issue by poblabs** [rothman857/chronometer#13]
In your reddit screenshot you show the full words for (second, minute, hour, century, etc) as well as when DST ends. I'm not seeing that. Is there a config option I missed?

Fun project - Thanks!

![image](https://user-images.githubusercontent.com/3484775/62711683-7be8de00-b9c7-11e9-9ca9-fe2f78c8b3ec.png)

**Comment by rothman857** [comment]
No, the reddit screenshot is outdated.  I went for a slightly more minimalist look.

**Comment by poblabs** [comment]
Ah too bad. You should have a config to allow long or short names.
