### ISSUE TITLE
how do I modify config?

### ISSUE THREAD

**Issue by Warhols** [rothman857/chronometer#15]
I can't get it out of default settings. When I sudo nano chronometer.py and edit my lat/long and default time zones, it has no effect on my changes when I run python3 chronometer.py.

Is there a config file I have to modify Instead? If so, where is it? 

Pi3 Buster

**Comment by rothman857** [comment]
Look for a .config file in the chronometer.py directory.  It was generated when you first ran chronometer.py.  Edit the .config file, and not chronometer.py.  Run ls -la if you don't see it.

**Comment by Warhols** [comment]
Thanks!  That did it. I didn't know -la was a thing. Appreciate it!
