### ISSUE TITLE
ModuleNotFoundError: No module named 'ephem'

### ISSUE THREAD

**Issue by scottchiefbaker** [rothman857/chronometer#4]
When I try and run this I get:

```
Traceback (most recent call last):
  File "./chronometer.py", line 7, in <module>
    import ephem
ModuleNotFoundError: No module named 'ephem'
```

No mention of `ephem` in the README, not sure where to get it.

**Comment by alangerak** [comment]
You have to install this in your python environment (with for instance `pip install <package>`)

- [ephem](https://pypi.org/project/ephem/)
- [pytz](https://pypi.org/project/pytz/)
